  image: java:8-jdk
  
  stages:
    - test
    - build
    
  maven-test:
    image: maven:3.5.2-jdk-8
    stage: test
    script: "mvn test"
    
  maven-build:
    image: maven:3.5.2-jdk-8
    stage: build
    script: "mvn package"
    artifacts:
      paths:
        - target/*.jar

  variables:
    MYSQL_DATABASE: "mybooksusersdb"
    MYSQL_USER: "app_root"
    MYSQL_PASSWORD: "root"
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_URL: jdbc:mysql://mysql/mybooksusersdb?createDatabaseIfNotExist=true"
    #MONGO_DATABASE: "??"
    #MONGO_HOST: "mongo"
    #MONGO_PORT: "27017"
  cache:
    paths:
      - .m2/repository
      - target