  image: java:8-jdk
  
  stages:
    - test
    - build
    
  maven-test:
    image: maven:3.5.2-jdk-8
    stage: test
    script: "mvn test"
    
  maven-build:
    image: maven:3.5.2-jdk-8
    stage: build
    script: "mvn package"
    artifacts:
      paths:
        - target/*.jar